# see https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#anaconda-iso-installer-options-installer-mapping
[customizations.installer.kickstart]
contents = """Add commentMore actions
%post
bootc switch --mutate-in-place --transport registry ghcr.io/esteve/ublue:latest
%end
"""
